### ISSUE TITLE
Расположение лампочки

### ISSUE THREAD

**Issue by realMaxA** [silverbulleters/vsc-spellchecker#6]
При позиционировании курсора на неизвестном слове лампочка располагается над текущей редактируемой строкой. В случае, если редактируемая строка "завёрнута" на несколько строк редактора, то лампочка может располагаться сильно выше текущего положения курсора.
Ожидаемое место появления лампочки: начало или конец "проблемного" слова.

**Comment by nixel2007** [comment]
Лампочкой мы не можем управлять, её рисует сам vsc
